### ISSUE TITLE
BUG: Wrong cast in StreamExtensions.WriteEnum

### ISSUE THREAD

**Issue by micdenny** [Syroot/BinaryData#12]
There's an `Int64` that should be `UInt64`

[StreamExtensions.Writing.cs#L700](https://github.com/Syroot/BinaryData/blob/master/src/Syroot.BinaryData/Extensions/StreamExtensions.Writing.cs#L700)

```csharp
            else if (valueType == typeof(UInt64))
            {
                converter.GetBytes((Int64)value, buffer, 0);
            }
```

**Comment by RayKoopa** [comment]
Fixed with https://github.com/Syroot/BinaryData/commit/6cc5c57a66214f44f5fdd5f379febcdc2c803b9d
