### ISSUE TITLE
Add missing unit tests

### ISSUE THREAD

**Issue by RayKoopa** [Syroot/BinaryData#18]
Unit tests have been added quite late to the library, and test coverage is still not fully satisfying. For the upcoming release 5 of the library, full coverage should be made a high priority.

Add / check for missing unit tests for the following:

- [x] ByteConverter (all methods)
- [x] StreamExtensions (general methods)
- [x] StreamExtensions (7BitInt32)
- [x] StreamExtensions (Boolean)
- [x] StreamExtensions (Byte)
- [x] StreamExtensions (DateTime)
- [x] StreamExtensions (Decimal)
- [x] StreamExtensions (Double)
- [x] StreamExtensions (Enum)
- [x] StreamExtensions (Int16)
- [x] StreamExtensions (Int32)
- [x] StreamExtensions (Int64)
- [x] StreamExtensions (SByte)
- [x] StreamExtensions (Single)
- [x] StreamExtensions (String)
- [x] StreamExtensions (UInt16)
- [x] StreamExtensions (UInt32)
- [x] StreamExtensions (UInt64)
- [x] StreamExtensions (Object)
- [x] BinaryStream (general methods)
- [x] BinaryStream (Boolean)
- [x] BinaryStream (DateTime)
- [x] BinaryStream (Double)
- [x] BinaryStream (Enum)
- [x] BinaryStream (Int16)
- [x] BinaryStream (Int32)
- [x] BinaryStream (Int64)
- [x] BinaryStream (Single)
- [x] BinaryStream (String)
- [x] BinaryStream (UInt16)
- [x] BinaryStream (UInt32)
- [x] BinaryStream (UInt64)
- [ ] BinaryStream (Object)

**Comment by micdenny** [comment]
just one unit test left, cheering for you!! 😄 I'm going to upgrade to v5, great job, thank you @RayKoopa !

**Comment by RayKoopa** [comment]
Ignoring Object tests for now, Serialization features have not been drastically changed since old tests anyway.
