### ISSUE TITLE
Write Object not implemented

### ISSUE THREAD

**Issue by jhett12321** [Syroot/BinaryData#25]
Currently in the 5.0.0 beta, object writing functionality is not currently implemented (throws when using the stream extension)

Will this be added for the 5.0.0 release?

**Comment by RayKoopa** [comment]
Serialization features have been split into a new package called `Syroot.BinaryData.Serialization`. Due to the amount of new features and limited time I have, it will be released at a later time, but definitely before 5 goes final.
