### ISSUE TITLE
The nuget package Syroot.BinaryData.Serialization has dependencies on the signed binaries instead of unsigned

### ISSUE THREAD

**Issue by micdenny** [Syroot/BinaryData#35]
Is this a mistake?

https://www.nuget.org/packages/Syroot.BinaryData.Serialization/5.0.0-alpha1

![image](https://user-images.githubusercontent.com/1633595/41152264-7262e0dc-6b13-11e8-991a-84dab0f19657.png)

I would expect to see the dependency on the unsigned `Syroot.BinaryData`

**Comment by RayKoopa** [comment]
Probably a copy-paste failure of the dependencies in the csproj. I'll fix it soon unless a PR is faster than me.

**Comment by RayKoopa** [comment]
Fixed with the final release.
