### ISSUE TITLE
BUG: WriteObject and ReadObject implementation is not deterministic

### ISSUE THREAD

**Issue by micdenny** [Syroot/BinaryData#6]
Those implementations relies on the [`Type.GetMember`](https://github.com/Syroot/BinaryData/blob/master/src/Syroot.BinaryData/Reflection/TypeData.cs#L28) method to get the fields/properties, but that method does **not guarantee any order**, so different compilation could produce different order and then could produce intermittent bugs that then are so difficult to understand (for instance the server use an order and the client use another one).

source: [Type.GetMembers Method](https://docs.microsoft.com/en-us/dotnet/api/system.type.getmembers?view=netframework-4.6#System_Type_GetMembers)
> The GetMembers method does not return members in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which members are returned, because that order varies.

**In my opinion this should be warned out in the repo readme.**

A possible solution could be to add an explicit order property on the [`BinaryMemberAttribute`](https://github.com/Syroot/BinaryData/blob/master/src/Syroot.BinaryData/Reflection/BinaryMemberAttribute.cs) class, so it can be specified.

**Comment by RayKoopa** [comment]
That's indeed ugly, I thought the order is as specified in the source. Your suggestion seems to be the only solution for me.

**Comment by micdenny** [comment]
> Your suggestion seems to be the only solution for me.

yeah, I can tell you I'm quite sure what I'm talking about, because in the past I did something similar, and for months the same code worked simply well, then it suddenly started to fire errors on errors and after we built again, the problem was fixed, then after some new features and a deploy, again the problem, you can bet was A NIGHTMARE!!! and then I found that sentence in the MSDN!

To me the only possible solution was to change the interface, make a very big breaking change, and force the developers passing the order of the fields, but that was configuration based, mean that the dev could pass an anonymous obj to configure the order of the fields, in this case instead, using the attribute, we cannot enforce at compile time, but if we want we can enforce at runtime, checking that all properties must have order set in the attribute if you use the Write/ReadObject method, this runtime check will introduce a big breaking change for those is relying on that method and obviously they don't have the order specified, but we can avoid this kind of check, but then you have a really fragile piece of code around, we can fire a issue where we ask if someone is using those methods, and tell them that they will have to add the appropriate attribute, wait some weeks, and then proceed with the breaking change.

**Comment by RayKoopa** [comment]
My current idea is to only do the required breaking changes and release a 4.0.0 in which the members are cached in a deterministic order as follows:

- The new `Order` attribute property has priority, but it is optional:
- Members not having this attribute will be sorted alphabetically behind all those having `Order` set.

I think this can be done nicely when caching the members in `TypeData`, using sorted lists.

Then I'll rewrite the [warning I just added to the wiki](https://github.com/Syroot/BinaryData/wiki/Object-Values) saying that pre-4 versions will behave fragile and should not be used anymore. Keeping the logic for people residing on 3 (or maybe still 2) untouched at all.

I was already rewamping most parts of serialization for 5.0.0 (no ETA) with multiple different attributes on members (s. https://github.com/Syroot/BinaryData/issues/4) to make it more flexible. Definitely the `Order` property will become its own attribute there now.

**Comment by micdenny** [comment]
I like the idea.

> Members not having this attribute will be sorted alphabetically behind all those having Order set.

also this is good, if someone doesn't care about the order but only about the deserialized object, it's ok.

> Then I'll rewrite the warning I just added to the wiki saying that pre-4 versions will behave fragile and should not be used anymore. Keeping the logic for people residing on 3 (or maybe still 2) untouched at all.

perfect!

**Comment by RayKoopa** [comment]
And this is how I will overtake Chrome in version numbering 😢

**Comment by RayKoopa** [comment]
Fixed with https://github.com/Syroot/BinaryData/commit/db8f837ef1ae9107a131c271446a8ff0bf708410
Release and NuGet is underway.
