### ISSUE TITLE
StringDataFormat.Raw not managed causing ArgumentException

### ISSUE THREAD

**Issue by micdenny** [Syroot/BinaryData#7]
I was trying to print a string in a raw format (fixed string) but I'm getting an ArgumentException:

```
System.ArgumentException: Invalid StringDataFormat.
Parameter name: format
   at Syroot.BinaryData.Extensions.StreamExtensions.Write(Stream stream, String value, StringDataFormat format, Encoding encoding, ByteConverter converter)
```

Look at the code it simply lack the `case StringDataFormat.Raw:`  implementation.

Work around if you're good with `Unicode` rappresentation:

```csharp
writer.Write(mystring.ToCharArray());
```

or this to manage the Encoding:

```csharp
writer.Write(Encoding.UTF8.GetBytes(mystring));
```

**Comment by micdenny** [comment]
I pushed a PR #8 

I understand that simply doing `Write(Encoding.UTF8.GetBytes(mystring))` could be the right approach, but when you see the `Raw` option from the enum, it seems you are legitimated to use it, otherwise it should be removed to avoid misunderstanding.

**Comment by RayKoopa** [comment]
Good call, no clue how that one was missed. Merged your PR; would you like a NuGet package update?

**Comment by micdenny** [comment]
> Good call, no clue how that one was missed. Merged your PR

thank you

> would you like a NuGet package update?

I'm not in hurry about this.

**Comment by RayKoopa** [comment]
Alright, I'll plan it for the next release then.
